# please run ./p to run all my code 
runCode:
	gcc deframe.c -o d;
	gcc deframeUppercase.c -o du;
	gcc framing.c -o f;
	gcc framingUppercase.c -o fu;
	gcc encode.c -o c;
	gcc encodeuppercase.c -o cu;
	gcc parityremove.c -o prm;
	gcc decode.c -o dec;
	gcc decodeUpper.c -o decodeu;
	
	gcc producerconsumer.c -o p;
